python run.py --model_type electra \
              --model_name_or_path google/electra-large-discriminator \
              --do_train \
              --do_eval \
              --per_gpu_train_batch_size 8 \
              --num_train_epochs 2 \
              --gradient_accumulation_steps 12 \
              --learning_rate 5e-5 \
              --warmup_steps 100 \
              --overwrite_output_dir \
              --output_dir ./electra_result